name: Continuous Integration

on: 
  pull_request:
    paths-ignore:
      - README.md

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: rootpass 
          MYSQL_DATABASE: cosmic_news_bd  
        options: --health-cmd="mysqladmin ping --silent" --health-start-period=30s

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests in cosmic-news directory
        run: mvn -f cosmic-news/pom.xml test

      - name: Generate Docker image
        run: |
          mvn spring-boot:build-image -DskipTests \
          -Dspring-boot.build-image.imageName=${{ secrets.DOCKERHUB_USERNAME }}/cosmic-news:v1

      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
          -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/cosmic-news:v1